spring:
   application:
      name: oidc-demo

   datasource:
      url: jdbc:mysql://localhost:3306/oidc?createDatabaseIfNotExist=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

   jpa:
      hibernate:
         ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5Dialect

   security:
      oauth2:
         client:
            registration:
               google:
                  clientId: ${GOOGLE_APP_CLIENT_ID}
                  clientSecret: ${GOOGLE_APP_CLIENT_SECRET}
                  scope:
                     - email
                     - profile
                     - openid

   config:
      import: optional:file:.env[.properties]
